#!/bin/bash -l
#SBATCH --time=00:00:05
#SBATCH --nodes=1
#SBATCH --mem=2G
#SBATCH --ntasks-per-node=1
#SBATCH --sockets-per-node=1
#SBATCH --partition=m1,m2,m3
#SBATCH --job-name=md_simul
#SBATCH --output=JOB.o

T=$1
dMOT=$2
Beam=$3
P_b=$4
Heating=$5

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# running
source /home/software/materia/intel/oneapi/setvars.sh --force
module load python3.10
mpirun -np 56 python3 simulation.py $T $dMOT $Beam $P_b $Heating
